# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_alta_turno.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NuevoTurno(object):
    def setupUi(self, NuevoTurno):
        NuevoTurno.setObjectName("NuevoTurno")
        NuevoTurno.resize(758, 422)
        self.label_nuevo_turno = QtWidgets.QLabel(NuevoTurno)
        self.label_nuevo_turno.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_nuevo_turno.setFont(font)
        self.label_nuevo_turno.setObjectName("label_nuevo_turno")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(NuevoTurno)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 360, 301, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_guardar = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout.addWidget(self.btn_guardar)
        self.btn_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.label = QtWidgets.QLabel(NuevoTurno)
        self.label.setGeometry(QtCore.QRect(490, 20, 261, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagenes/depilacion-con-cera.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(NuevoTurno)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 71, 426, 266))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_cliente = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cliente.setFont(font)
        self.label_cliente.setObjectName("label_cliente")
        self.horizontalLayout_2.addWidget(self.label_cliente)
        self.text_cliente = QtWidgets.QLineEdit(self.layoutWidget)
        self.text_cliente.setObjectName("text_cliente")
        self.horizontalLayout_2.addWidget(self.text_cliente)
        self.combo_box_clientes = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_box_clientes.setObjectName("combo_box_clientes")
        self.horizontalLayout_2.addWidget(self.combo_box_clientes)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_servicios = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_servicios.setFont(font)
        self.label_servicios.setObjectName("label_servicios")
        self.horizontalLayout_3.addWidget(self.label_servicios)
        self.list_servicios = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_servicios.setFont(font)
        self.list_servicios.setObjectName("list_servicios")
        self.horizontalLayout_3.addWidget(self.list_servicios)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_box_servicios = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_box_servicios.setObjectName("combo_box_servicios")
        self.verticalLayout_2.addWidget(self.combo_box_servicios)
        self.btn_eliminas_servicio = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_eliminas_servicio.setToolTip("")
        self.btn_eliminas_servicio.setObjectName("btn_eliminas_servicio")
        self.verticalLayout_2.addWidget(self.btn_eliminas_servicio)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_fecha = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_fecha.setFont(font)
        self.label_fecha.setObjectName("label_fecha")
        self.horizontalLayout_4.addWidget(self.label_fecha)
        self.fecha_turno = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.fecha_turno.setObjectName("fecha_turno")
        self.horizontalLayout_4.addWidget(self.fecha_turno)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(NuevoTurno)
        QtCore.QMetaObject.connectSlotsByName(NuevoTurno)

    def retranslateUi(self, NuevoTurno):
        _translate = QtCore.QCoreApplication.translate
        NuevoTurno.setWindowTitle(_translate("NuevoTurno", "Nuevo turno"))
        self.label_nuevo_turno.setText(_translate("NuevoTurno", "Nuevo Turno"))
        self.btn_guardar.setText(_translate("NuevoTurno", "Guardar"))
        self.btn_cancelar.setText(_translate("NuevoTurno", "Cancelar"))
        self.label_cliente.setText(_translate("NuevoTurno", "Cliente:"))
        self.label_servicios.setText(_translate("NuevoTurno", "Servicios:"))
        self.btn_eliminas_servicio.setText(_translate("NuevoTurno", "Eliminar Servicio"))
        self.label_fecha.setText(_translate("NuevoTurno", "Fecha:"))

